// micartapro-console/src/lib/components/Sidebar.svelte
<script lang="ts">
  interface SidebarProps {
    activeSection: string
    onSectionChange: (section: string) => void
    isOpen?: boolean
    onClose?: () => void
  }

  let { activeSection, onSectionChange, isOpen = true, onClose }: SidebarProps = $props()
</script>

<div 
  class="w-64 bg-gray-900 text-white h-screen fixed left-0 top-0 z-40 shadow-xl transform transition-transform duration-300 ease-in-out md:translate-x-0 {isOpen ? 'translate-x-0' : '-translate-x-full'}"
>
  <div class="p-6 border-b border-gray-700 flex items-center justify-between">
    <h2 class="text-xl font-bold text-white">MiCartaPro</h2>
    <!-- Botón cerrar para móvil -->
    <button
      onclick={onClose}
      class="md:hidden p-2 hover:bg-gray-800 rounded-lg transition-colors"
      aria-label="Cerrar menú"
    >
      <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>
  
  <nav class="px-4 py-4">
    <button
      onclick={() => onSectionChange('menu')}
      class={`w-full flex items-center p-3 rounded-lg transition-all duration-200 mb-2 ${
        activeSection === 'menu' 
          ? 'bg-blue-600 text-white shadow-md' 
          : 'text-gray-300 hover:bg-gray-800 hover:text-white'
      }`}
    >
      <svg class="w-5 h-5 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      <span class="text-sm font-medium">Menú</span>
    </button>

    <button
      onclick={() => onSectionChange('galeria')}
      class={`w-full flex items-center p-3 rounded-lg transition-all duration-200 mb-2 ${
        activeSection === 'galeria' 
          ? 'bg-blue-600 text-white shadow-md' 
          : 'text-gray-300 hover:bg-gray-800 hover:text-white'
      }`}
    >
      <svg class="w-5 h-5 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      <span class="text-sm font-medium">Galería</span>
    </button>
  </nav>
</div>

// electric/src/components/Sidebar.tsx
interface SidebarProps {
  isOpen: boolean
  onClose: () => void
  routeStarted: boolean
  onDownloadReport: () => void
  syncInfo?: {
    deviceId: string
  } | null
  markerPosition?: {
    visitIndex: number
    coordinates: [number, number]
    timestamp: number
    deviceId: string
  } | null
}

export function Sidebar({ 
  isOpen, 
  onClose, 
  routeStarted, 
  onDownloadReport,
  syncInfo,
  markerPosition
}: SidebarProps) {
  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50">
      {/* Overlay */}
      <div 
        className="absolute inset-0 bg-black/40 backdrop-blur-sm transition-opacity duration-300"
        onClick={onClose}
      ></div>
      
      {/* Sidebar Panel */}
      <div className="absolute top-0 left-0 h-full w-80 bg-white shadow-2xl transform transition-transform duration-300 ease-out">
        {/* Header */}
        <div className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white p-6">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold">Menú</h2>
            <button 
              onClick={onClose}
              className="bg-white/20 hover:bg-white/30 rounded-lg p-2 transition-colors duration-200"
              aria-label="Cerrar menú"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        
        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Botón CSV */}
          {routeStarted && (
            <div className="space-y-2">
              <h3 className="text-sm font-semibold text-gray-600 uppercase tracking-wide">Reportes</h3>
              <button
                onClick={() => {
                  onDownloadReport()
                  onClose()
                }}
                className="w-full bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white p-4 rounded-xl font-medium transition-all duration-200 shadow-lg hover:shadow-xl active:scale-95 flex items-center justify-center space-x-3"
                aria-label="Descargar reporte"
              >
                <span className="text-2xl">📊</span>
                <span>Descargar Reporte</span>
              </button>
            </div>
          )}
          
          {/* Indicadores de conexión */}
          <div className="space-y-2">
            <h3 className="text-sm font-semibold text-gray-600 uppercase tracking-wide">Estado de Conexión</h3>
            <div className="bg-gray-50 rounded-xl p-4 space-y-3">
              {/* Estado de conexión a internet */}
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-gray-700">Internet</span>
                <div className="flex items-center space-x-2">
                  {navigator.onLine ? (
                    <>
                      <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                      <span className="text-sm text-green-600 font-medium">Conectado</span>
                    </>
                  ) : (
                    <>
                      <div className="w-2 h-2 bg-red-500 rounded-full"></div>
                      <span className="text-sm text-red-600 font-medium">Desconectado</span>
                    </>
                  )}
                </div>
              </div>
              
              {/* Estado de sincronización GunJS */}
              {syncInfo && (
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-700">Sincronización</span>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></div>
                    <span className="text-sm text-blue-600 font-medium">
                      {syncInfo.deviceId.slice(-6)}
                    </span>
                  </div>
                </div>
              )}
              
              {/* Indicador de posición sincronizada */}
              {markerPosition && (Date.now() - markerPosition.timestamp) < 30000 && (
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-700">Marcador Sync</span>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-purple-500 rounded-full animate-pulse"></div>
                    <span className="text-sm text-purple-600 font-medium">
                      📍 {markerPosition.deviceId.slice(-6)}
                    </span>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
